version: '3.8'

services:
  h4x0r_b41t:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - h4x0r_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - h4x0r_network

networks:
  h4x0r_network:
    driver: bridge
